# Generated by Django 5.0.6 on 2024-07-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twodo',
            options={'ordering': ('complete',)},
        ),
        migrations.AddField(
            model_name='twodo',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='twodo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
